blank_issues_enabled: true
contact_links: # ссылочки
  - name: Наш Telegram
    url: https://t.me/CrimsonCoalition
    about: Тут вы можете задавать вопросы, следить за новостями проекта.
  - name: Сообщения о уязвимостях
    url: https://bounty.github.com/
    about: Пожалуйста, сообщите о уязвимостях здесь.
